source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.4.1'
gem 'rails', '~> 5.2.0'

gem "awesome_print"
gem "babel-transpiler"
gem "bootstrap-sass"
gem "coffee-rails"
gem "devise"
gem "jbuilder"
gem "jquery-rails"
gem "money-rails"
gem "pg"
gem "puma"
gem "pundit"
gem "sass-rails"
gem "simple_form"
gem "slim-rails", github: "slim-template/slim-rails"
gem "sprockets", '~> 3.7.2'
gem "turbolinks"
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "uglifier"
gem 'bootsnap', require: false

group :development do
  gem "foreman"
  gem "listen"
  gem "rails_layout"
  gem "slim_lint"
  gem "spring-commands-rspec"
  gem "spring-watcher-listen"
  gem "spring"
  gem "web-console"
end

group :development, :test do
  gem "byebug", platform: :mri
  gem "factory_bot"
  gem "faker"
  gem "pry-rails"
  gem "pry-rescue"
  gem "rspec-rails"
  gem "rubocop"
end

group :test do
  gem "capybara-screenshot"
  gem "capybara"
  gem "database_cleaner"
  gem "launchy"
  gem "selenium-webdriver"
end